version: "3.9"

services:
  # Dev: hot reload, bind mounts, dev target
  web:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: next-dev
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
      - WATCHPACK_POLLING=true
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - supabase-local
    networks:
      - app-network

  # Prod: optimized image from final stage (runner)
  web-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      # final stage is 'runner' so no target needed
    image: next-app:prod
    container_name: next-prod
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  # Local Supabase proxy (when not using CLI)
  supabase-local:
    profiles: ["dev"]
    image: nginx:alpine
    container_name: supabase-proxy
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "54321:54321"
    networks:
      - app-network
    command: ["nginx", "-g", "daemon off;"]
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
